name: Clone Repository Workflow

on:
  push:
    branches:
      - "*"

jobs:
  clone_repository:
    runs-on: ubuntu-latest

    steps:
      - name : Get Branch Name
        id : branch-names
        uses: tj-actions/branch-names@v8

      - name : Get Base Ref branch names (i.e The target of a pull request.)
        run : |
            echo "${{ steps.branch-names.outputs.base_ref_branch }}" 
       
     
      