name: Update TOC

on:
  push:
    branches:
      - master

jobs:
  update-toc:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install markdown-toc
        run: npm install markdown-toc

      - name: Update TOC
        run: npx markdown-toc -i README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md
          git commit -m "Update TOC"
          git push
