name: Clone Repository Workflow

on:
  pull_request:
    branches:
      - "*"

jobs:
  clone_repository:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        run: |
          # Retrieve the complete branch name directly from the GitHub context
          FULL_BRANCH_NAME=${{ github.head_ref }}
          
          # Extract just the branch name without the 'refs/heads/' prefix
          BRANCH_NAME=$(basename $FULL_BRANCH_NAME)
          
          # Clone the specified repository using the extracted branch name
          git clone --branch $BRANCH_NAME https://github.com/PalisadoesFoundation/talawa-admin.git
