name: Clone Repository Workflow

on:
  pull_request:
    branches:
      - '*'

jobs:
  clone_repository:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Print current branch
        run: |
          # Extract the branch name from the pull request ref
          branch_name=$(echo "${{ github.ref }}" | awk -F'/' '{print $4}')
          echo "Current branch: $branch_name"

      - name: Clone different repository
        run: |
          # Clone the specified repository
          git clone https://github.com/PalisadoesFoundation/talawa-api.git
          
          # Navigate into the cloned repository
          cd repository
          
          # Checkout the branch corresponding to the pull request's head reference
          git checkout ${{ github.head_ref }}
