on:
    pull_request:
      branches:
        - main
  
  ...
      steps:
        - name: Get branch names
          id: branch-names
          uses: tj-actions/branch-names@v8
        
        - name: Current branch names
          run: |
            echo "${{ steps.branch-names.outputs.current_branch }}"
          # Outputs: "feature/test" current PR branch.
  
        - name: Running on a non tag based branch and a PR branch.
          if: steps.branch-names.outputs.is_default == 'false'
          run: |
            echo "Running on branch: ${{ steps.branch-names.outputs.current_branch }}"
          # Outputs: "Running on branch: feature/test".
        
        - name: Running on a pull request (i.e non tag based branch).
          if: steps.branch-names.outputs.is_tag == 'false' && steps.branch-names.outputs.is_default == 'false'
          run: |
            echo "Running on branch: ${{ steps.branch-names.outputs.current_branch }}"
          # Outputs: "Running on branch: feature/test".
        
        - name: Get Ref branch name
          run: |
            echo "${{ steps.branch-names.outputs.ref_branch }}"
          #  Outputs: "1/merge"
  
        - name: Get Head Ref branch names (i.e The current pull request branch)
          run: |
            echo "${{ steps.branch-names.outputs.head_ref_branch }}"
          # Outputs: "feature/test" current PR branch.
  
        - name: Get Base Ref branch names (i.e The target of a pull request.)
          run: |
            echo "${{ steps.branch-names.outputs.base_ref_branch }}"
          # Outputs: "main".
        
        - name: Default branch names
          run: |
            echo "${{ steps.branch-names.outputs.default_branch }}"
          # Outputs: "main" the default branch.