name: Print Branch Name

on:
  push:
    branches:
      - '**'

jobs:
  print-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Print Branch
        run: echo "The branch name is ${{ github.ref }}"
